apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: jirongling/sit323-task9p:latest  
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongouser:secret@mongo-service:27017/?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
